@startuml componentDiagram
left header
<font size=20 color=black>Robotarm Component diagram </font>
endheader
left to right direction

    [MotionPlanner] --( IAction


component rosnode{
    component HighLevelInterface
    [HighLevelInterface] -- [Driver]
    [HighLevelInterface] -- IAction
    

}
    [Driver] --( IArmAction
component robotArm{
}
    robotArm -- IArmAction

@enduml