@startuml
left to right direction


    [MotionPlanner] --( IPreDefinedPosition
    [MotionPlanner] --( IConfigPosition
    [MotionPlanner] --( IEmergencyStop


component rosnode{
    component highLevelInterface
    [highLevelInterface] --( IMove
    [highLevelInterface] --( IStop
    [highLevelInterface] -- IPreDefinedPosition
    [highLevelInterface] -- IConfigPosition
    [highLevelInterface] -- IEmergencyStop
    
    component driver
    [driver] -- IMove
    [driver] -- IStop
    [driver] -- writeMessage
}

component robotArm{
    component Arm
    component SCC32U
    [SCC32U] --( writeMessage
    [Arm] --( writePosition
    [SCC32U] -- writePosition
}

@enduml