@startuml protocolStateMachine

left header
<font size=20 color=black>Robotarm Protocol state diagram{protocol} </font>
endheader

left to right direction
State Moving
State Idle
State EmergencyStop

[*]-> Moving : moveToPark
Moving --> Idle : [currentTime >= timeToMove] positionReached 
Moving --> EmergencyStop : emergencyStop
Idle --> EmergencyStop : emergencyStop

EmergencyStop --> [*]
@enduml