@startuml stateDiagram
left header
<font size=30 color=black>RobotArm State diagram </font>
endheader
left to right direction

state Startup
Startup : Entry /
Startup : Do / "Initialiseer (read configuration)"
Startup : Exit /

state Moving
Moving : Entry /
Moving : Do / "moveToPosition(newPosition)"
Moving : Exit/ "Check current position"

state Calibrate
Calibrate : Entry / 
Calibrate : Do / "calibrate"
Calibrate : Exit / "Check current position"

state Park
Park : Entry /
Park : Do / "Move to park position"
Park : Exit /

state Idle
Idle : Entry /
Idle : Do / 
Idle : Exit /

state emergencyStop
emergencyStop : Entry /
emergencyStop : Do /
emergencyStop : Exit /


[*] --> Startup
Startup -> Calibrate : [configFound == false] calibrate
Startup -> Park : [configFound == true] park
Park ---> Moving : move 
Moving --> Idle : [currentPosition == newPosition] idle
Moving --> Park : [currentPosition == parkPosition] park
Idle --> Moving : move
Idle --> Park : moveToPark
Calibrate --> Moving : move
Moving --> Calibrate : [currentPosition == newPosition] calibrate
Calibrate --> Park : [calibrated == true && currentPosition == parkPosition] park

Calibrate --> emergencyStop : emergencyStop
Startup --> emergencyStop : emergencyStop
Idle --> emergencyStop : emergencyStop
Moving --> emergencyStop : emergencyStop
Park --> emergencyStop : emergencyStop

emergencyStop -> [*] : stop
Park --> [*] : stop

@enduml

