@startuml
top to bottom direction

Actor MotionPlanner
Actor Arm

rectangle HighLevelInterface {
    MotionPlanner -> (Stuur noodstop)
    MotionPlanner -> (Stuur standaard positie)
    MotionPlanner -> (Stuur positie inclusief tijd)
    (Roep driver aan) .-right-> (Stuur positie inclusief tijd) : extend
    (Roep driver aan) .-right-> (Stuur noodstop) : extend
    (Roep driver aan) .-right-> (Stuur standaard positie) : extend
}

rectangle Driver {
    Arm -left-> (Verstuur bericht naar arm)
    (Controleer bericht) .> (Roep driver aan) : include
    (Controleer bericht) .> (Verstuur bericht naar arm) : extend
}

@enduml