@startuml
left to right direction
Actor MotionPlanner
Actor RobotArm

rectangle RobotArmbesturing {
    MotionPlanner -> (Stuur positie inclusief tijd)
    MotionPlanner -> (Stuur noodstop)
    (Controleer of positie binnen grenzen valt) .> (Stuur positie inclusief tijd) : include
    (Stuur bericht naar robotarm) .> (Stuur noodstop) : include
    (Stuur positie inclusief tijd) .> (Stuur bericht naar robotarm) : extends
    RobotArm -> (Stuur bericht naar robotarm)
}

@enduml