@startuml
left to right direction

Actor User
Actor MotionPlanner

rectangle Driver{
    (Check message) <. (Send message) : Extends
}

rectangle HighLevelDriver{
    (Set position) .> (Set time) : extends
    (Set preprogrammed position)
    (Emergency stop)
    (Set offset)
    (Display information)
}

rectangle robotArm{
    (Move to position)
    (Save offset)
    (Emergency stop )
}

User --> (Set offset)
User --> (Emergency stop)
MotionPlanner --> (Set preprogrammed position)
MotionPlanner --> (Set position)


(Emergency stop) --> (Send message)
(Set position) --> (Check message)
(Set preprogrammed position) --> (Send message)
(Set offset) --> (Check message)

(Send message) <.. (Move to position) : Extends
(Send message) <.. (Save offset) : Extends
(Send message) <.. (Emergency stop ) : Extends
@enduml